# Generated by Django 4.2.1 on 2023-11-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_customuser_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Alumno', 'alumno'), ('Profesor', 'profesor')], max_length=15, verbose_name='Rol')),
                ('materia', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=100, null=True)),
                ('horarios_disponibles', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
