# Generated by Django 4.2.1 on 2023-11-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_usuario_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
