# Generated by Django 4.2.1 on 2023-11-03 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
