# Generated by Django 4.2.1 on 2023-11-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0006_delete_usuariopersonalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], default='alumno', max_length=10)),
                ('materia', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
