# Generated by Django 4.2.1 on 2023-11-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
