# Generated by Django 4.2.1 on 2023-11-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='profesor',
        ),
    ]
